#!/bin/bash

VAGRANT_VERSION=1.7.4
VIRTUALBOX_VERSION=5.0.8
VIRTUALBOX_FULL_VERSION=5.0.8-103449

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install ansible wget

cd /tmp
wget -Nq https://dl.bintray.com/mitchellh/vagrant/vagrant_$VAGRANT_VERSION.dmg
hdiutil attach ./vagrant_$VAGRANT_VERSION.dmg
sudo installer -package /Volumes/Vagrant/Vagrant.pkg -target /

wget -Nq http://download.virtualbox.org/virtualbox/$VIRTUALBOX_VERSION/VirtualBox-$VIRTUALBOX_FULL_VERSION-OSX.dmg
hdiutil attach ./VirtualBox-$VIRTUALBOX_FULL_VERSION-OSX.dmg
sudo installer -package /Volumes/VirtualBox/VirtualBox.pkg -target /
